version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    build:
      context: ./docker/alertmanager/
    volumes:
      - ./docker/alertmanager/alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build:
      context: ./docker/prometheus/
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/alertmanager/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    build:
      context: ./docker/grafana/
    volumes:
      - ./docker/grafana/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./docker/grafana/grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000